src/main/java/PoorToRich/PoorToRich/email/controller/MailController.java
src/main/java/PoorToRich/PoorToRich/email/enums/EmailResponse.java
src/main/java/PoorToRich/PoorToRich/email/facade/EmailFacade.java
src/main/java/PoorToRich/PoorToRich/email/response/VerificationResendCodeStatusResponse.java
src/main/java/PoorToRich/PoorToRich/email/service/EmailVerificationService.java

남은 인증 코드 재발급 횟수를 조회 API
- `email`을 통해 남은 인증 코드 재발급 횟수를 조회하는 기능을 추가하였습니다.
- 만약 인증 코드를 **발급받지 않았다면** 최대 횟수를 반환하고,
- 발급받았다면 **최대 횟수에서 차감된 횟수**를 반환합니다.
---
- `@RequestParam`을 사용하여 `email`을 받아오고, 해당 값을 검증하기 위해 `@Valid` 애너테이션을 사용했으나, 예상했던 `MethodArgumentNotValidException` 대신 `ConstraintViolationException`이 발생했습니다.
- **원인**: `@RequestParam`과 `@PathVariable`에서 발생하는 검증 오류는 `ConstraintViolationException`을 발생시키므로, 이를 처리하기 위한 **`ExceptionHandler` 추가**가 필요합니다.
- `@Email` 애너테이션의 검증이 일부 이메일 형식에서 제대로 동작하지 않는 문제가 발생했습니다.
- **예시**:
- `[O] example@ex.com`
- `[O] example@dsad`
- `[X] example@`
- `[X] example`
- `@Email` 검증이 `example@dsad`와 같은 이메일을 **허용**하는 문제 발견.  
→ `@Email`의 기본 검증 규칙이 너무 느슨하여 예상하지 못한 이메일을 허용함.
발견된 문제의 경우 차후 해결 예정

feat: 인증 코드 재발급 횟수 조회 API

---

src/main/java/com/poortorich/PoorToRichApplication.java
src/main/java/com/poortorich/category/controller/CategoryController.java
src/main/java/com/poortorich/category/repository/CategoryRepository.java
src/main/java/com/poortorich/category/request/CategoryInfoRequest.java
src/main/java/com/poortorich/category/response/CategoryInfoResponse.java
src/main/java/com/poortorich/category/response/CategoryResponse.java
src/main/java/com/poortorich/category/service/CategoryService.java

- 카테고리의 정보를 반환하기 위한 DTO 생성
- 예외 처리를 위한 필드를 추가
--|--|--
`NON_EXISTENT_ID` | NOT_FOUND (404) | 조회된 값이 존재하지 않는 경우
- 매개변수로 들어온 `Id` 값으로 카테고리 조회
- 만약 조회된 값이 없는 경우 `NotFoundException` 예외를 던지도록 구현
- `@PathVariable` 로 `categoryId` 값을 받아옴
---
- 전체적인 패키지명 변경으로 인한 오류 발생으로 인한 `PoorToRichApplication` Entity 경로 수정
- `CategoryRepository` Id 값의 형식 변경 
`BigInteger` > `Long` 변경
- 객체 이름의 통일성을 위한 이름 변경 
`CustomeCategoryRequest` > `CategoryInfoRequest`
> 조회에 성공한 경우
> 조회에 실패한 경우

[#30] 카테고리 조회 API 구현

---

src/main/java/com/poortorich/category/controller/CategoryController.java
src/main/java/com/poortorich/category/entity/Category.java
src/main/java/com/poortorich/category/response/CategoryResponse.java
src/main/java/com/poortorich/category/service/CategoryService.java
src/main/java/com/poortorich/category/validator/CategoryValidator.java

- entity 변경을 위한 값 수정 메소드 추가
`updateCategory`
> setter 를 사용하지 않고 메소드의 목적을 알 수 있도록 명시적인 이름을 작성하여 구현하였습니다. 
- 예외처리를 위한 필드 추가
--|--|--
`SUCCESS_MODIFY_CATEGORY` | CREATED (201) | 카테고리 편집 성공
- 필드 이름 및 메세지 수정
`NON_EXISTENT_ID` > `NON_EXISTENT_CATEGORY`
- 같은 이름이 있는 경우, id 값을 찾을 수 없는 경우 예외 처리를 진행
- 성공적으로 업데이트가 됐다면, entity 값을 변경하고 `categoryRepository` 에 저장
> `@Transactional` 어노테이션을 사용하는 게 맞는지 고민중입니다 ,,
- 카테고리를 편집할 때 이름을 변경하지 않는 경우, **기존의 중복 이름 검증 로직**에서 예외를 발생
⇒ **중복 이름 검증 로직**을 **오버로딩**하여 id 값이 같은 경우는 검사하지 않도록 추가 구현
> 편집 성공
> 중복된 카테고리 이름으로 변경 시
> 존재하지 않는 아이디 값 전달 시
- service 로직에 `@Transactional` 어노테이션 사용 고려
---
- `@Transactional` 어노테이션 추가
- Entity `@DynamicUpdate` 어노테이션 추가 
변경된 값만 업데이트

[#32] 카테고리 편집 API 구현

---

src/main/java/com/poortorich/category/controller/CategoryController.java
src/main/java/com/poortorich/category/response/CategoryResponse.java
src/main/java/com/poortorich/category/service/CategoryService.java

- `deleteCategory` 구현
- 중복되는 카테고리 조회 코드 분리
> 조회, 수정, 삭제에 걸쳐 id 값으로 카테고리를 조회하고, 존재하지 않으면 예외를 던지는 코드가 반복됐습니다. `getCategoryOrThrow` 메소드를 만들어 코드를 분리했습니다.
- 카테고리 삭제 성공 필드 추가
--|--|--
`SUCCESS_DELETE_CATEGORY` | OK (200) | 성공적으로 카테고리를 삭제
> 삭제에 성공한 경우
> 존재하지 않는 카테고리인 경우

[#34] 카테고리 삭제 API 구현

---

src/main/java/com/poortorich/category/controller/CategoryController.java
src/main/java/com/poortorich/category/entity/CategoryType.java
src/main/java/com/poortorich/category/response/ActiveCategoriesResponse.java
src/main/java/com/poortorich/category/response/CategoriesResponse.java
src/main/java/com/poortorich/category/response/CategoryResponse.java
src/main/java/com/poortorich/category/response/DefaultCategoriesResponse.java
src/main/java/com/poortorich/category/service/CategoryService.java
src/main/java/com/poortorich/global/handler/GlobalExceptionHandler.java

- `@RequestParam` 값이 비어있을 경우 `MissingServletRequestParameterException` 예외가 발생
- `GlobalExceptionHandler` 에 해당 예외 핸들러를 추가
상수 `MISSING_PARAMETER` 를 사용하여 에러 메세지를 반환하도록 구현
- 예외 처리에 필요한 필드 추가
--|--|--
`INVALID_CATEGORY_TYPE` | BAD REQUEST (400) | 카테고리 타입 값이 적절하지 않은 경우
- Map을 사용하여 입력으로 들어오는 `type` 값과 `CategoryType` 값을 매핑
- `from` 메소드를 사용하여 매개변수로 들어온 `type` 값에 맞는 `CategoryType` 값을 반환
**적절한 키 값이 없는 경우 `BadRequestException` 예외를 던짐**
- `type` 값이 일치하고, `visbility` 값이 _true_인 **category entity의 name**을 반환
- List로 변경하는 코드 변경
> `collect(Collectors.toList())` 에서 반환되는 List는 수정이 가능하기 때문에 문제가 발생할 수 있다고 판단했습니다. 따라서 수정이 불가능한 List을 반환하는 `toList()` 로 변경하였습니다.
- `Controller` `Service` 메소드 순서 변경
> /category/{categoryId} 에 매핑될 수 있는 가능성이 있기 때문에 코드의 순서를 변경하여 /category/active end point를 먼저 처리할 …

[#36] 활성화된 카테고리 조회 API 구현

---

src/main/java/com/poortorich/PoorToRichApplication.java
src/main/java/com/poortorich/category/repository/CategoryRepository.java
src/main/java/com/poortorich/category/service/CategoryService.java
src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
src/main/java/com/poortorich/expense/constants/ExpenseValidationConstraints.java
src/main/java/com/poortorich/expense/controller/ExpenseController.java
src/main/java/com/poortorich/expense/entity/Expense.java
src/main/java/com/poortorich/expense/entity/enums/IterationType.java
src/main/java/com/poortorich/expense/entity/enums/PaymentMethod.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
src/main/java/com/poortorich/expense/request/ExpenseRequest.java
src/main/java/com/poortorich/expense/response/ExpenseResponse.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/global/constants/DatePattern.java
src/main/java/com/poortorich/security/config/SecurityConfig.java
src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
src/test/java/com/poortorich/expense/fixture/ExpenseApiFixture.java
src/test/java/com/poortorich/expense/fixture/ExpenseFixture.java
src/test/java/com/poortorich/expense/fixture/enums/CategoryNameValidationCase.java
src/test/java/com/poortorich/expense/fixture/enums/CostValidationCase.java
src/test/java/com/poortorich/expense/fixture/enums/DateValidationCase.java
src/test/java/com/poortorich/expense/fixture/enums/MemoValidationCase.java
src/test/java/com/poortorich/expense/fixture/enums/TitleValidationCase.java
src/test/java/com/poortorich/expense/request/ExpenseConverterTest.java
src/test/java/com/poortorich/expense/request/ExpenseRequestValidTest.java
src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java
src/test/java/com/poortorich/expense/util/ExpenseRequestTestBuilder.java
src/test/java/com/poortorich/global/util/RequestValidTestHelper.java

- Category Entity와 `ManyToOne` 연관관계 설정
- `iterationType`을 Enum 타입으로 설정
> 로그인이 구현된 후 User 연관관계를 설정하기 위해, 현재는 주석처리를 해두었습니다.
- 성공 및 예외 처리에 필요한 필드 추가
> title, paymentMethod, iterationType 관련 필드는 `@Valid`로 처리하지 못하는 예외 처리를 위해 선언하였습니다.
- `title`의 경우, null 값을 허용하기 때문에 `@Size(min = 1)` 을 사용하는 경우 null 값까지 예외처리가 되어 따로 예외 처리를 진행하였습니다. 
-- | -- | --
CREATE_EXPENSE_SUCCESS | CREATED (201) | 지출 가계부를 성공적으로 등록
TITLE_TOO_SHORT | BAD REQUEST (400) | 지출 제목의 길이가 1 이하일 경우 (null 제외)
PAYMENT_METHOD_INVALID | BAD REQUEST (400) | 지출수단이 유효하지 않은 경우
ITERATION_TYPE_INVALID | BAD REQUEST (400) | 반복데이터가 유효하지 않은 경우
- `@Valid` 검증을 위한 어노테이션을 적절히 선언
API 명세서를 기반으로 작성하였습니다.
- Enum 값 `PaymentMethod` `IterationType` 의 parse 메서드 작성
- `title`의 **1자 이하 문자열 예외처리**를 위해 `trimTitle` 메서드 작성
- `Category`와 …

[#41] 지출 가계부 추가 API 구현

---

src/main/java/com/poortorich/global/response/BaseResponse.java
src/main/java/com/poortorich/global/response/DataResponse.java

data 필드를 가지는 기본 응답 형식을 추가하였음.
BaseResponse를 상속하며 SuperBuilder를 통해 부모-자식간 필드 빌드 가능
< Trouble Shooting >
DataResponse를 제너릭 타입을 사용해 선언하였으나 Builder 사용 시 타입을 찾지 못하는 문제가 발생하였음. data 필드의 타입을 Object로 수정하여 해결함.

[#54] 응답 형식 리팩터링

---

src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
src/main/java/com/poortorich/expense/controller/ExpenseController.java
src/main/java/com/poortorich/expense/entity/Expense.java
src/main/java/com/poortorich/expense/entity/enums/IterationType.java
src/main/java/com/poortorich/expense/entity/enums/PaymentMethod.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
src/main/java/com/poortorich/expense/response/ExpenseInfoResponse.java
src/main/java/com/poortorich/expense/response/ExpenseResponse.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
src/main/java/com/poortorich/iteration/entity/enums/EndType.java
src/main/java/com/poortorich/iteration/entity/enums/IterationRuleType.java
src/main/java/com/poortorich/iteration/entity/enums/MonthlyMode.java
src/main/java/com/poortorich/iteration/entity/enums/Weekday.java
src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
src/main/java/com/poortorich/iteration/response/CustomIterationInfoResponse.java
src/main/java/com/poortorich/iteration/response/EndInfoResponse.java
src/main/java/com/poortorich/iteration/response/IterationRuleInfoResponse.java
src/main/java/com/poortorich/iteration/response/MonthlyOptionInfoResponse.java
src/main/java/com/poortorich/iteration/service/IterationService.java
src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java

#67 
- `IterationInfo` 정보를 얻기 위해 `IterationExpenses`와 양방향 매핑 관계를 맺도록 설정
- 연관관계의 주인은 `generatedExpense` 필드로 설정
- 반복 타입 조회를 하기 위해 `@DiscriminatorColumn`의 `iterationType` 필드에 접근할 수 있도록 추가
- `getIterationTypeLowerCase()`
: `iterationType`을 소문자 형태로 반환하는 메서드
> 모든 Type 관련 필드들이 enum String 형태로 저장되기 때문에 다른 테이블의 형식에 맞춰 `iterationType`을 대문자로 저장했습니다. (`@DiscirminatorColumn`은 enum 지정 불가) 
> 출력시 소문자 형태로 전달해줘야 하는데, 문자열이 짧고 변환하는 데에 드는 비용이 별로 크지 않다고 생각하여 `toLowerCase()`를 사용하게 되었습니다.
- 각 enum 타입마다 value 값 출력이 필요하기 때문에 **toString 재정의**
- 지출 조회시 필요한 Reseponse 값을 추가
-- | -- | --
GET_EXPENSE_SUCCESS | OK (200) | 지출 가계부 조회 성공
EXPENSE_NON_EXISTENT | NOT_FOUND (404) | 지출 가계부 조회 실패
- 지출 가계부 정보를 담는 responseDTO
- 사용자화 반복 데이터 정보를 담는 responseDTO
- 사용자화 반복 데이터에서 각 타입 별로 필요한 값만 전달될 수 있도록 …

[#67] 지출 가계부 조회 API 구현

---

src/main/java/com/poortorich/user/constants/UserResponseMessages.java
src/main/java/com/poortorich/user/controller/UserController.java
src/main/java/com/poortorich/user/entity/User.java
src/main/java/com/poortorich/user/facade/UserFacade.java
src/main/java/com/poortorich/user/request/PasswordUpdateRequest.java
src/main/java/com/poortorich/user/response/enums/UserResponse.java
src/main/java/com/poortorich/user/service/UserService.java
src/main/java/com/poortorich/user/service/UserValidationService.java
src/main/java/com/poortorich/user/validator/UserValidator.java
src/test/java/com/poortorich/user/controller/UserControllerTest.java
src/test/java/com/poortorich/user/facade/UserFacadeTest.java
src/test/java/com/poortorich/user/service/UserServiceTest.java
src/test/java/com/poortorich/user/service/UserValidationServiceTest.java
src/test/java/com/poortorich/user/util/PasswordUpdateRequestTestBuilder.java
src/test/java/com/poortorich/user/validator/UserValidatorTest.java

비밀번호 변경 API를 추가했습니다.
- `Request Body`가 유효한지 검증합니다.
- 비밀번호를 갱신합니다.
- 현재 비밀번호가 일치하는지 검증합니다.
- 새 비밀번호와 새비밀번호 확인 필드가 서로 같은지 검증합니다.
- 현재 비밀번호가 요청한 회원의 비밀번호가 일치하는지 비교합니다.
- 틀렸다면 예외를 던집니다.
- 새로운 비밀번호로 갱신합니다.
컨벤션 위배 
`newPassword`와 `confirmNewPassword`가 서로 같은지 비교하는 로직에서 서로 틀리다면 `UserResponse.PASSWORD_DO_NOT_MATH` 예외를 던지도록 구현되어있습니다.
이는 회원가입을 구현할 때 구현하였는데 서로 다른 경우 field 데이터가 `password`로 클라이언트에게 전달되는 문제를 발견했습니다.
(__해당 API에서 문제가 되는 필드명은 `confirmNewPassword`입니다__ )
이를 회피하기 위해서는 다른 로직을 구성해서 구현할 필요가 있어보입니다.

[#83] 비밀번호 변경 API

---

src/main/java/com/poortorich/expense/request/ExpenseRequest.java
src/main/java/com/poortorich/global/date/constants/DateConstants.java
src/main/java/com/poortorich/global/date/constants/DatePattern.java
src/main/java/com/poortorich/global/date/domain/MonthInformation.java
src/main/java/com/poortorich/global/date/domain/WeekInformation.java
src/main/java/com/poortorich/global/date/domain/YearInformation.java
src/main/java/com/poortorich/global/date/util/DateInfoProvider.java
src/main/java/com/poortorich/iteration/request/End.java
src/test/java/com/poortorich/expense/fixture/ExpenseFixture.java
src/test/java/com/poortorich/global/date/fixture/DateTestFixture.java
src/test/java/com/poortorich/global/date/util/DateInfoProviderTest.java

연별/월별/주별 합계&통계를 계산하기 위해 날짜 범위와 정보를 제공하는 객체를 추가하였습니다. 
* 해당연도 시작날과 마지막날을 __`LocalDate`__ 로 제공
* 1월부터 12월까지의 __MonthInformation__ 을 `Month enum`을 통해 조회할 수 있는 맵을 제공
* 해당월의 시작날과 마지막날을 __`LocalDate`__ 로 제공
* 첫째주부터 마지막주까지의 __WeekInformation__을 `List<>`로 제공합니다.
* 해당 주의 시작날과 마지막날을 __`LocalDate`__ 로 제공
해당 연도의 시작날과 마지막날을 계산하고 `getMonthInformation`을 Month enum을 통해 순회하며 계산합니다.
해당 월의 시작날과 마지막날을 계산하고 `getWeekInformation`을 통해 List<WeekInformation>`을 받아와 저장합니다.
해당 월의 첫 주부터 마지막 주까지 구간을 계산하여 저장한 `List<>`를 반환합니다. 주 계산은 아래와 같은 방법으로 진행합니다.
* 달력 기준 한 줄의 시작 날과 마지막 날을 계산하여 저장합니다.
* 주의 시작 요일은 일요일이며 마지막 요일은 토요일입니다. 
* 이는 통계를 낼 때 구간의 크기가 달라 비교의 어려움이 있어 __프론트와 상의 후 결정한 계산 방법__ 입니다.
* e. g.)
*  2025-05의 첫 주: __4월 27일 ~ 5월 3일__
*  2025-06의 마지막 주: __6월 29일 ~ 7월 5일__
getWeekInformation()의 메소드 명이 적절한거 같나요? 아니라면 다른 이름을 …

[#85] 날짜 정보를 제공하는 유틸 객체 추가

---

src/main/java/com/poortorich/global/response/BaseResponse.java
src/main/java/com/poortorich/global/response/DataResponse.java

#92 
resultCode -> `status`
resultMessage -> `message`
>

[#92] response 필드 이름 수정

---

src/main/java/com/poortorich/security/filter/auth/JwtAuthenticationFilter.java
src/test/java/com/poortorich/auth/controller/AuthControllerTest.java
src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
src/test/java/com/poortorich/security/filter/auth/JwtAuthenticationFilterTest.java
src/test/java/com/poortorich/user/controller/UserControllerTest.java
src/test/java/com/poortorich/user/validator/UserValidatorTest.java

#94 
- JWTFilter에 있는 Response builder의 응답 필드 이름을 수정
- Test에 있는 응답 필드 이름을 수정
- UserValidatorTest에서 실패하는 테스트를 수정
>

[#94] 응답 필드 수정에 영향을 받는 로직 수정

---

src/main/java/com/poortorich/category/constants/CategoryResponseMessage.java
src/main/java/com/poortorich/category/controller/CategoryController.java
src/main/java/com/poortorich/category/entity/Category.java
src/main/java/com/poortorich/category/request/CategoryVisibilityRequest.java
src/main/java/com/poortorich/category/response/CategoryResponse.java
src/main/java/com/poortorich/category/service/CategoryService.java

#96 
카테고리 활성화/비활성화 여부 수정에 대한 API를 구현하였습니다.
- 활성화/비활성화 정보를 받기 위한 Request
- 필수 입력값이기 때문에 `@NotNull` 어노테이션 사용
필드 | 상태 | 내용
--|--|--
CATEGORY_VISIBILITY_TRUE_SUCCESS | 200 (OK) | 카테고리가 활성화로 변경된 경우
CATEGORY_VISIBILITY_FALSE_SUCCESS | 200 (OK) | 카테고리가 비활성화로 변경된 경우
- 카테고리 활성화 여부를 업데이트하기 위한 메서드
- 카테고리 활성화/비활성화 여부를 변경하는 메서드
- `visibility` **true**
카테고리 **활성화** 성공이라는 Response 반환
- `visibility` **false**
카테고리 **비활성화** 성공이라는 Response 반환
- Request에 따라 적절하게 카테고리 활성화 여부를 변경하고 응답을 반환하는 메서드
> 활성화 성공
> <img width="643" alt="image" src="https://github.com/user-attachments/assets/670ddf3a-d070-44d7-a34d-9436eb1e0b88" />
> 비활성화 성공
> <img width="642" alt="image" src="https://github.com/user-attachments/assets/212a0a34-3e72-4c31-9f39-46a13320cc28" />
> 입력 값이 없는 경우
> <img width="500" alt="image" …

[#96] 카테고리 활성화/비활성화 API 구현

---

src/main/java/com/poortorich/category/service/CategoryService.java
src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
src/main/java/com/poortorich/expense/controller/ExpenseController.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
src/main/java/com/poortorich/expense/request/ExpenseDeleteRequest.java
src/main/java/com/poortorich/expense/request/enums/IterationAction.java
src/main/java/com/poortorich/expense/response/ExpenseResponse.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
src/main/java/com/poortorich/iteration/service/IterationService.java
src/main/java/com/poortorich/user/service/UserService.java
src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java

#86 
지출 수정 API 먼저 구현하고 있었으나, 지출 수정 기능 일부에 삭제 로직이 필요하다고 판단하여 지출 삭제 API를 먼저 구현하였습니다. 
- 반복데이터 지출 수정 / 삭제에 필요한 Enum
IterationAction | 사용 용도
--|--
NONE | 반복데이터가 아닌 지출 삭제
THIS_ONLY | (반복 지출데이터인 경우) 해당 데이터만 삭제
THIS_AND_FUTURE | (반복 지출데이터인 경우) 해당 데이터와 이후 데이터 삭제
ALL | (반복 지출데이터인 경우) 모든 데이터 삭제
> 반복데이터가 아닌 경우 `ExpenseDeleteRequest`에 `iterationAction` 값이 입력으로 들어오지 않습니다.
> 따라서 null이 들어오는 경우는 예외 처리 대상이 아니기 때문에 `NONE` 타입으로 바뀌도록 처리하였습니다.
- 지출 데이터가 **반복데이터인 경우에만** 사용되는 Request
`IterationAction.NONE`인 경우
- 입력으로 들어온 `expenseId` 값에 해당되는 지출 데이터만 삭제
`IterationAction.NONE`이 아닌 경우
- 입력으로 들어온 `expenseId`를 바탕으로 기준이 되는 지출데이터인 `targetExpense`를 얻음
-> `iterationService`에서 반환되는 `List<Expense>` 값을 모두 삭제
- 단일 Expense 삭제 메소드
- Expense들을 삭제하는 메소드
- `targetExpense`를 얻기 위해 필요하기 때문에 `public`으로 변경
- `IterationAction`을 기준으로 반복 …

[#86] 지출 가계부 삭제 API 구현

---

src/main/java/com/poortorich/category/domain/model/enums/DefaultExpenseCategory.java
src/main/java/com/poortorich/category/domain/model/enums/DefaultIncomeCategory.java
src/main/java/com/poortorich/category/repository/CategoryRepository.java
src/main/java/com/poortorich/category/service/CategoryService.java
src/main/java/com/poortorich/expense/entity/Expense.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/user/facade/UserFacade.java
src/main/java/com/poortorich/user/service/UserService.java
src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java

회원가입이 완료된 경우 지출&수입 기본 카테고리를 생성하여 저장하는 로직을 추가하였습니다.
지출 & 수입 기본 카테고리는 enum으로 관리하였습니다. 기본 카테고리가 수정되거나 추가될 때 해당 enum에 추가/수정하는 작업만으로 수정이 가능합니다. 
enum으로 프론트에서 제공한 디자인 정보를 활용하여 카테고리 이름과 색상을 표기하였습니다.
`DefaultExpenseCategory`와 같이 작업했습니다.
`DefaultExpenseCategory`와 `DefaultIncomeCategory`의 `toCategoryEntity(User)` 의 반환값을 DB에 저장합니다.
`UserRepository`로 저장한 __User Entity__ 를 반환하도록 수정
DB에 저장 후 반환된 __User Entity__ 를 사용하여 `CategoryService.saveAllDefaultCategories`를 호출하는 로직 추가
회원가입 후 기본 카테고리가 잘 저장되는 것을 확인하였음
1. 변수명, 메소드명, 객체명이 적절한지
2. 컨벤션 위배된 코드가 있는지
3. 다른 방식의 코드를 추천할게 있는지

[#101] 기본 카테고리 추가 기능 추가

---

src/main/java/com/poortorich/s3/service/FileUploadService.java
src/main/java/com/poortorich/user/request/UserRegistrationRequest.java

회원가입 시 프로필 이미지 필드를 null 허용하며 null이거나 비어있는 경우 기본 프로필 이미지를 반환하도록 수정하였음.

[#103] 회원가입 시 기본 프로필 적용

---

src/main/java/com/poortorich/accountbook/entity/AccountBook.java
src/main/java/com/poortorich/accountbook/response/InfoResponse.java
src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
src/main/java/com/poortorich/expense/entity/Expense.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
src/main/java/com/poortorich/income/controller/IncomeController.java
src/main/java/com/poortorich/income/entity/Income.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java
src/main/java/com/poortorich/income/response/IncomeInfoResponse.java
src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
src/main/java/com/poortorich/iteration/service/IterationService.java

#117 
- 수입 가계부 조회 API 구현
- `AccountBookService`에서 지출, 수입 두 가계부 모두 조회할 수 있도록 수정
- `generatedAccountBook`을 조회하기 위한 get 메서드를 추가
- `ExpenseInfoResponse`와 `IncomeInfoResponse`의 작업을 수행하기 위한 공통 로직을 위한 인터페이스
- 가계부 조회를 위한 메서드 `getIteration()` `getInfoResponse()` 추가
- `InfoResponse`를 AccountBookType에 따라 build하기 위한 메서드 추가 구현
- 수입 가계부 조회 성공 Response 추가
- 수입 가계부 조회 관련 메서드 구현
- `IterationIncome`과의 연관관계 설정
- `getGeneratedIteration()` 재정의
- 수입 가계부 정보를 담는 Response
- `getGeneratedIteration()` 재정의
- `ExpenseService` 대신 `AccountBookService`를 호출하도록 수정
- `InfoResponse` 인터페이스 구현
- `AccountBookService`로 로직을 합침에 따른 필요 없는 메서드 삭제
- `Iteration`으로 변경
- 코드 컨벤션 및 네이밍

[#117] 수입 가계부 조회 API 구현

---

src/main/java/com/poortorich/accountbook/entity/AccountBook.java
src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/expense/entity/Expense.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
src/main/java/com/poortorich/income/controller/IncomeController.java
src/main/java/com/poortorich/income/entity/Income.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java
src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
src/main/java/com/poortorich/income/service/IncomeService.java
src/main/java/com/poortorich/iteration/entity/Iteration.java
src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
src/main/java/com/poortorich/iteration/entity/IterationIncomes.java
src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
src/main/java/com/poortorich/iteration/repository/IterationIncomesRepository.java
src/main/java/com/poortorich/iteration/repository/IterationRepository.java
src/main/java/com/poortorich/iteration/service/IterationService.java

#119 
- 수입 가계부 편집 API 구현
- 가계부 편집 공통 로직 통합
- update 로직 추가
- 공통되는 가계부 편집 로직 추가
- 기존의 update() 메서드 삭제 후 `AccountBook` update() 메서드 재정의
- 공통되는 로직 통합을 위해 인터페이스(`AccountBook` `Iteration`)를 사용하도록 수정
- `AccountBookService`로 이전한 공통 로직 삭제
- 수입 가계부 편집 성공 response 추가
- 수입 가계부 편집 로직 추가
- update() 메서드 재정의
- 수입 가계부 편집 로직 추가
- 사용되지 않는 메서드 삭제
- 날짜 변경 메서드 추가
- originalAccountBook 을 update하는 메서드 추가
- update() 메서드 재정의
- `@Query` 어노테이션을 사용하는 메서드의 이름 수정
- 반복데이터 조회 관련 로직 추가
- 공통된 repository 로직을 처리하기 위한 메서드 추가
- 수입/지출 가계부 모두에서 사용할 수 있도록 인터페이스를 활용하여 로직 수정
- 코드 컨벤션 및 네이밍

[#119] 수입 가계부 편집 API 구현

---

src/main/java/com/poortorich/accountbook/repository/AccountBookRepository.java
src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
src/main/java/com/poortorich/chart/controller/ChartController.java
src/main/java/com/poortorich/chart/facade/ChartFacade.java
src/main/java/com/poortorich/chart/response/CategoryLineResponse.java
src/main/java/com/poortorich/chart/response/enums/ChartResponse.java
src/main/java/com/poortorich/chart/service/ChartService.java
src/main/java/com/poortorich/chart/util/PeriodFormatter.java
src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
src/main/java/com/poortorich/global/date/constants/DateResponseMessage.java
src/main/java/com/poortorich/global/date/response/enums/DateResponse.java
src/main/java/com/poortorich/income/repository/IncomeRepository.java

* 카테고리 꺾은선 그래프 API
* 구간 포맷터
`startDate`와 `endDate`를 인수로 받아 문자열 범위 데이터를 제공합니다.
* startDate = LocalDate.of(2025, 05, 01) & endDate = LocalDate.of(2025, 05, 31)
* `"2025.05.01~2025.05.31"`
* `"05.01~05.31"`
`RequestParam`으로 요청한 date에 해당하는 달의 총 금액과 각 주의 지출 총액을 제공합니다.

[#127] 카테고리 꺾은선 그래프 API

---

src/main/java/com/poortorich/accountbook/entity/AccountBook.java
src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
src/main/java/com/poortorich/global/date/util/DateParser.java
src/main/java/com/poortorich/income/entity/Income.java
src/main/java/com/poortorich/report/constants/ReportResponseMessages.java
src/main/java/com/poortorich/report/controller/ReportController.java
src/main/java/com/poortorich/report/facade/ReportFacade.java
src/main/java/com/poortorich/report/response/DailyDetailsResponse.java
src/main/java/com/poortorich/report/response/enums/ReportResponse.java
src/main/java/com/poortorich/report/service/ReportService.java

#126 
- 일별 상세 내역 조회 API 구현
- 날짜 변환 클래스 구현
- `getPaymentMethod()` `getCreatedDate()` 메서드 추가
- `AccountBookInfoResponse` build 메서드 추가
- `AccountBookInfoResponse` build 메서드 추가에 따른 코드 수정
- 날짜 문자열이 들어왔을 때 null인 경우 현재 날짜를 반환
- `LOCAL_DATE_PATTERN` 패턴에 맞는 문자열인 경우 LocalDate 객체로 변환
- 패턴이 맞지 않다면 `BadRequest` 예외 발생
- `getPaymentMethod()` 재정의 -> null을 반환하도록 구현
- 일별 상세 내역 성공 응답 메세지 추가
- 일별 상세 내역 로직 추가
- 각 AccountBook 마다 입력 날짜에 맞는 List 값을 받아온 뒤 `DailyDetailsResponse`로 가공하여 반환
- `getDailyDetailsReport()`
각 AccountBook의 총합을 구한 뒤 `getDailyAccountBookDetails()` 메서드에서 병합된 리스트를 `AccountBookInfoResponse`로 변환
모든 정보를 합쳐 `DailyDetailsResponse` 반환
- `getDailyAccountBookDetails()`
각 AccountBook 리스트 병합
- `inferAccountBookType()`
AccountBook의 타입을 유추
paymentMethod 값이 있는 경우 `expense` 타입, null인 경우 `income` 타입 반환
- 코드 …

[#126] 일별 상세 내역 API 구현

---

src/main/java/com/poortorich/accountbook/request/AccountBookDeleteRequest.java
src/main/java/com/poortorich/expense/controller/ExpenseController.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/expense/service/ExpenseService.java
src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
src/main/java/com/poortorich/income/controller/IncomeController.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java
src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java

#135 
- 수입 가계부 삭제 API 구현
- 삭제 Request 객체를 공통으로 사용하기 위해 추가
- 기존의 `ExpenseDeleteRequest`는 삭제
- `ExpenseDeleteRequest` 삭제, `AccountBookDeleteRequest` 사용에 따른 코드 수정
- `AccountBookService`로 로직을 이동함에 따라 사용하지 않게된 메서드 삭제
- 수입 삭제 API 관련 코드 추가
- 코드 컨벤션

[#135] 수입 가계부 삭제 API 구현

---

src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
src/main/java/com/poortorich/chart/controller/ChartController.java
src/main/java/com/poortorich/chart/facade/ChartFacade.java
src/main/java/com/poortorich/chart/response/enums/ChartResponse.java
src/main/java/com/poortorich/chart/service/ChartService.java
src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
src/test/java/com/poortorich/chart/controller/ChartControllerTest.java
src/test/java/com/poortorich/chart/facade/ChartFacadeTest.java
src/test/java/com/poortorich/chart/service/ChartServiceTest.java

* 기존에 구현되었던 지출 총액 및 저축 총액 API 비즈니스 로직을 수입에서도 동일하게 사용할 수 있게끔 수정
* 해결되지 않은 충돌 파일들 재처리
* 테스트 코드(통과하도록만) 수정

[#129] 수입 총액 및 저축 총액 조회 API

---

src/main/java/com/poortorich/category/entity/enums/CategoryType.java
src/main/java/com/poortorich/category/repository/CategoryRepository.java
src/main/java/com/poortorich/category/service/CategoryService.java

#138 
- 카테고리 이름 중복 검사를 하는 로직 수정
> 원래는 이름과 유저 정보만을 가지고 카테고리를 찾는 `findCategoryByName()` 메서드를 사용하여 이름 중복을 검사했습니다. 이 경우 다른 가계부 타입일 경우에도 이름이 중복되면 예외 응답을 던지는 이슈가 발생했습니다. 
> 그 문제를 해결하기 위해 카테고리 이름 중복 검사를 하는 새로운 메서드를 추가로 구현하였습니다.
- 같은 타입인 것들을 List로 묶어 반환
> expense => DEFAULT_EXPENSE, CUSTOM_EXPENSE
> income => DEFAULT_INCOME, CUSTOM_INCOME
- `CategotyType` 리스트에 있는 타입인 카테고리 중 같은 이름이 있는 경우 카테고리값 반환
- 카테고리 이름이 중복인지 검증하는 메서드
- user, name, type 값을 기반으로 카테고리 이름이 중복이라면 `BadRequest` 예외 발생
- `validateCategoryNameDuplication()` 메서드를 사용하여 카테고리 이름 중복 검증을 진행하도록 수정
> 지출에서 사용중인 카테고리 이름이지만 수입에서 생성하는 경우 예외 발생없이 생성 완료
- 코드 컨벤션 및 네이밍

[#138] 카테고리 이름 중복 검사 로직 수정

---

src/main/java/com/poortorich/email/facade/EmailFacade.java

프론트 요청에 따라 이메일 인증 코드 전송 로직에서 중복을 확인하는 로직을 추가했습니다.

[#156] 이메일 인증 로직에서 이메일 중복 확인 추가

---

src/main/java/com/poortorich/auth/jwt/constants/JwtConstants.java

프론트엔드에서 **AccessToken 재발급 API**를 호출하는 과정에서 쿠키가 포함되지 않아 `401 Unauthorized` 응답이 발생한 것으로 확인되었습니다.  쿠키의 `HTTPS` 설정에서 문제가 생긴 것으로 판단하여 수정 작업을 착수했지만 실제 원인은 다른 부분에서 발견했습니다. 쿠키의 `path` 필드에 다른 `endpoint`를 기입하여 문제가 발생한 것임을 파악했습니다.
수정 후 테스트 결과 `200 OK` 응답을 받았습니다.

[#158] 요청 시 쿠키 누락 문제 해결

---

src/main/java/com/poortorich/category/response/DefaultCategoryResponse.java
src/main/java/com/poortorich/category/service/CategoryService.java

#166 
- 기본 카테고리 조회 API에 사용되는 응답에 ID 필드 추가

[#166] 기본 카테고리 조회 응답 필드 추가

---

src/main/java/com/poortorich/category/repository/CategoryRepository.java
src/main/java/com/poortorich/category/service/CategoryService.java

#168 
- 활성화된 카테고리 목록 조회 로직 수정
- CategoryType 리스트 안의 값과 같은 카테고리를 조회하는 메서드
- `User`과 `Type` 순서 변경

[#168] 활성화된 카테고리 목록 조회 로직 수정

---

src/main/java/com/poortorich/accountbook/entity/enums/IterationType.java
src/main/java/com/poortorich/accountbook/response/AccountBookInfoResponse.java
src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java

#170 
- 응답 객체에 빠져있던 반복데이터 확인 필드를 추가하였습니다.

[#170] 반복데이터 확인 필드 추가

---

src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
src/main/java/com/poortorich/income/response/enums/IncomeResponse.java

#172 
- `getAccountBookOrThrow()` 메서드에서 가계부 조회에 실패한 경우 `AccountBookType`에 따라 응답을 다르게 반환하도록 수정

[#172] 존재하지 않는 수입 가계부 응답 수정

---

src/main/java/com/poortorich/category/domain/model/enums/DefaultExpenseCategory.java

[#189] 기본 지출 카테고리 이름 오타 수정

---

src/main/java/com/poortorich/user/response/UserDetailResponse.java
src/main/java/com/poortorich/user/service/UserService.java

* 프로필 조회시 isDefaultProfile 필드를 추가하여 현재 프로필 사진이 기본 프로필인지 여부를 클라이언트에게 제공

[#197] 프로필 상세 조회 때 isDefaultProfile 추가

---

src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/chart/util/PeriodFormatter.java
src/main/java/com/poortorich/report/facade/ReportFacade.java
src/main/java/com/poortorich/report/service/ReportService.java

#178 
- 조회 에러 수정
해당 주차에 데이터가 없는 경우 정상적인 응답을 반환하도록 예외 처리
- countOfLogs 값 수정
해당 기간에 존재하는 모든 가계부의 개수 값을 반환하도록 수정
- period 문자열 수정
` - ` -> ` ~ ` 로 수정
> 해당 주차에 데이터가 없는 경우 응답
> <img width="879" alt="image" src="https://github.com/user-attachments/assets/7e1c4ef2-4652-4b22-aaab-19be84f92cba" />

[#178] 주별 수입/지출 상세내역 수정

---

src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java
src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
src/main/java/com/poortorich/iteration/repository/IterationIncomesRepository.java
src/main/java/com/poortorich/iteration/repository/IterationRepository.java
src/main/java/com/poortorich/iteration/service/IterationService.java

#199
- 반복 지출/수입 데이터 조회를 할 때 유저가 두 명 이상인 경우 제대로 조회되지 않는 오류 발생
-> 반복 데이터 조회 로직에 `user` 조건 추가

[#199] 반복 지출/수입 데이터 조회 수정

---

src/main/java/com/poortorich/category/service/CategoryService.java

#203
- 프론트 요청에 따라 `기타` 카테고리가 항상 맨 뒤에 있도록 정렬 방식 수정

[#203] 활성화된 카테고리 정렬 방식 수정

---

src/main/java/com/poortorich/category/service/CategoryService.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java

#201
- 지출/수입 타입이 같은 카테고리를 조회하는 로직을 추가한 후 그 로직을 사용하도록 수정

[#201] 가계부 추가/편집 카테고리 조회 로직 변경

---

src/main/java/com/poortorich/accountbook/response/AccountBookCreateResponse.java
src/main/java/com/poortorich/expense/controller/ExpenseController.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/income/controller/IncomeController.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java
src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java

#205
- 프론트 요청사항에 따라 가계부를 추가하는 경우 추가된 가계부의 ID 값을 반환하도록 수정

[#205] 가계부 추가 응답 데이터 추가

---

src/main/java/com/poortorich/user/service/UserService.java

- 프론트 요청에 따라 기본 프로필인 경우 null로 제공하도록 수정

[#216] 프로필 조회시 기본프로필인 경우 null로 제공

---

src/main/java/com/poortorich/accountbook/response/AccountBookActionResponse.java
src/main/java/com/poortorich/expense/controller/ExpenseController.java
src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
src/main/java/com/poortorich/income/controller/IncomeController.java
src/main/java/com/poortorich/income/facade/IncomeFacade.java

#222
- 프론트 요청에 따라 가계부 추가, 편집, 삭제 응답을 추가한 후 카테고리 아이디를 반환하도록 구현하였습니다.
추가
편집
삭제
>

[#222] 가계부 추가, 편집, 삭제 응답에 카테고리 아이디 추가

---

src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/chart/facade/ChartFacade.java

- [ 시작 날 ] ~ [ 끝 날 ]에 해당하는 가계부 개수를 반환하는 로직을 추가
- 이를 통해 카테고리 구간 내역의 총 개수를 가져와서 처리

[#234] 카테고리 구간 내역 총 내역 수 조회 로직 수정

---

Dockerfile
src/main/java/com/poortorich/iteration/constants/IterationResponseMessages.java
src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
src/main/java/com/poortorich/iteration/entity/IterationIncomes.java
src/main/java/com/poortorich/iteration/entity/info/DailyIterationRule.java
src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
src/main/java/com/poortorich/iteration/entity/info/MonthlyIterationRule.java
src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
src/main/java/com/poortorich/iteration/entity/info/YearlyIterationRule.java
src/main/java/com/poortorich/iteration/mapper/IterationMapper.java
src/main/java/com/poortorich/iteration/provider/IterationCalculatorProvider.java
src/main/java/com/poortorich/iteration/service/IterationService.java
src/main/java/com/poortorich/iteration/util/IterationBuilder.java
src/main/java/com/poortorich/iteration/validator/MonthlyOptionValidator.java

#242
- 프론트엔드의 요청에 따라 반복데이터 매달 옵션일 때의 모든 값을 요청으로 받고 응답으로 반환하도록 수정
- Entity의 `@NoArgsConstructor`의 access level을 `PROTECTED`로 변경
- 반복데이터 중 날짜 계산을 하는 로직의 분기문들을 모아둔 클래스
- Entity와 관련된 Builder를 모아둔 클래스
- DTO와 관련된 Builder를 모아둔 클래스
- 클래스 이름 네이밍
- 반복데이터 관련 더 필요한 리팩토링

[#242] 반복데이터 리팩토링

---

src/main/java/com/poortorich/accountbook/service/AccountBookService.java
src/main/java/com/poortorich/auth/service/AuthService.java
src/main/java/com/poortorich/chart/collector/ChartDataCollector.java
src/main/java/com/poortorich/chart/facade/ChartFacade.java
src/main/java/com/poortorich/chart/factory/ChartResponseFactory.java
src/main/java/com/poortorich/chart/util/PeriodFormatter.java
src/main/java/com/poortorich/user/controller/UserController.java
src/main/java/com/poortorich/user/facade/UserFacade.java
src/main/java/com/poortorich/user/request/EmailUpdateRequest.java
src/main/java/com/poortorich/user/service/UserService.java

이번 QA에서 발생한 각종 오류를 수정하였음
1. 차트 페이지 총 금액 및 저출/투자 총액 조회 API에서 **저축/추자 총 금액** 조회 오류 수정
2. 차트 페이지 수직형 막대그래프 조회에서 날짜 포맷팅 오류 수정
3. 카테고리 상세 내역 조회 API에서 총 내역 건수 오류 수정
4. 회원 탈퇴 시 토큰 삭제하는 로직을 추가
5. 이메일 변경 DTO 필드명을 newEmail에서 email로 수정

[#253] QA 오류 수정

---

src/main/java/com/poortorich/category/repository/CategoryRepository.java
src/main/java/com/poortorich/category/service/CategoryService.java

#261
- 카테고리 편집시 이름을 변경하지 않았을 때 (ex. 색상만 변경한 경우) 잘못된 오류 수정
- 카테고리 편집시 같은 아이디인 경우 조회되지 않는 새로운 Repository 메서드 추가
>  ![image](https://github.com/user-attachments/assets/e120c8c6-db3f-4163-9f3f-82fc83511b1b)
> 색상만 변경한 경우 잘 변경됨
>

[#261] 카테고리 편집 오류 수정

---

src/main/java/com/poortorich/admin/constants/AdminResponseMessage.java
src/main/java/com/poortorich/admin/controller/AdminController.java
src/main/java/com/poortorich/admin/facade/AdminFacade.java
src/main/java/com/poortorich/admin/request/UserRoleUpdateRequest.java
src/main/java/com/poortorich/admin/response/enums/AdminResponse.java
src/main/java/com/poortorich/admin/service/UserManagementService.java
src/main/java/com/poortorich/security/config/SecurityConfig.java
src/main/java/com/poortorich/user/constants/UserResponseMessages.java
src/main/java/com/poortorich/user/controller/UserController.java
src/main/java/com/poortorich/user/entity/User.java
src/main/java/com/poortorich/user/entity/enums/Role.java
src/main/java/com/poortorich/user/facade/UserFacade.java
src/main/java/com/poortorich/user/response/UserRoleResponse.java
src/main/java/com/poortorich/user/response/enums/UserResponse.java

- 프론트에서 현재 회원의 역할을 확인하기 위한 API입니다.
- `ADMIN` 역할에서만 호출할 수 있으며 임의로 특정 회원의 역할을 변경할 수 있습니다.

[#265] 회원 역할 조회 및 수정 API

---

src/main/java/com/poortorich/page/domain/Pagination.java

차트 카테고리 상세 내역 조회 API에서 내역 조회가 끝났음에도
nextCursor=true로 반환되는 현상을 발견하였음
클라이언트에서 이 값을 사용하여 한 번 더 조회하여 중복 데이터가 발생
서버 내부 코드 확인 결과 날짜를 오름차순으로 정렬한 데이터의 마지막
데이터 정보에서 다음 커서 여부를 확인하여 생긴 문제 이를 수정

[#280] 차트 상세 내역 중복 데이터 조회 수정

---

src/main/java/com/poortorich/auth/oauth2/service/CustomOAuth2UserService.java
src/main/java/com/poortorich/s3/constants/S3Constants.java
src/main/java/com/poortorich/user/controller/UserController.java
src/main/java/com/poortorich/user/facade/UserFacade.java
src/main/java/com/poortorich/user/response/OAuthUserDetailResponse.java
src/main/java/com/poortorich/user/service/UserService.java

프론트 요청에 따라 OAuth 회원 상세 조회 API를 수정했습니다.
- profileImage 필드
- 카카오 기본 프로필일 경우
```jsx
profileImage: null 
isDefaultProfile: true
```
- nickname 필드
- 현재 카카오 닉네임 값을 가져옴
- 요청 사항 : 카카오 닉네임값은 name 필드 매칭해주세요
=> 닉네임 중복 검사 문제 때문에 카카오 닉네임을 이름필드값으로 사용하는게 좋을 것 같다고 판단
- nickname 필드 빼고 repsonse 보내기
- name 필드
- 카카오 닉네임값 매칭
- birth 필드
- birth  필드 빼고 repsonse 보내기
- gender 필드
- 현재 기본값 :  MALE
- 요청 기본 값: FEMALE
- job 필드
- 현재 기본 값 : null
- 요청 기본 값 : 선택안함

[#302] OAuth 회원 상세 조회 API 요구사항 적용

---

build.gradle
docker-compose.yml
src/main/java/com/poortorich/auth/kakao/service/KakaoService.java
src/main/java/com/poortorich/user/facade/UserFacade.java
src/main/resources/application.properties

카카오 회원이 탈퇴하는 경우 동의 정보 내역 파기를 위해 카카오와 연결을 해제하는 로직을 추가했습니다.

[#309] 회원탈퇴 시 카카오 연결 해제 로직 추가

---

src/main/java/com/poortorich/chat/controller/ChatController.java
src/main/java/com/poortorich/chat/entity/ChatMessage.java
src/main/java/com/poortorich/chat/facade/ChatFacade.java
src/main/java/com/poortorich/chat/request/ChatroomCreateRequest.java
src/main/java/com/poortorich/tag/service/TagService.java
src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java

#316
#318 과 이어지는 PR입니다.
- 채팅메세지 누락 필드 추가
- 하나의 Request를 사용하도록 로직 수정
> 현재 추가 로직은 정상적으로 작동하나, webp 변경 부분에서 문제가 있는 것으로 확인됩니다 
> <img width="840" height="253" alt="image" src="https://github.com/user-attachments/assets/d8eeddfc-f842-4ad4-83d7-cd3066c7740c" />
> 이 문제 발생 시 response 필드 값이 `proflieImage`로 전송되고 있어서, field 값을 지정해주는 방식의 변경이 필요할 거 같습니다
> <img width="798" height="434" alt="image" src="https://github.com/user-attachments/assets/04b8c1f8-4829-4fb9-882e-f15936d2a2f5" />
>

[#316] 채팅방 추가 API 수정사항

---

src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
src/main/java/com/poortorich/chat/controller/ChatController.java
src/main/java/com/poortorich/chat/facade/ChatFacade.java
src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
src/main/java/com/poortorich/chat/response/ChatroomInfoResponse.java
src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
src/main/java/com/poortorich/chat/service/ChatroomService.java
src/main/java/com/poortorich/chat/util/ChatBuilder.java
src/main/java/com/poortorich/tag/repository/TagRepository.java
src/main/java/com/poortorich/tag/service/TagService.java
src/test/java/com/poortorich/chat/controller/ChatControllerTest.java
src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
src/test/java/com/poortorich/tag/service/TagServiceTest.java

#325
- 채팅방 조회 API
- `chatroomId`로 `Chatroom`과 `Tag`를 조회한 뒤 필요한 정보를 반환

[#325] 채팅방 조회 API 구현

---

src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
src/main/java/com/poortorich/chat/controller/ChatParticipantController.java
src/main/java/com/poortorich/chat/facade/ChatFacade.java
src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
src/main/java/com/poortorich/chat/response/ChatroomResponse.java
src/main/java/com/poortorich/chat/response/ChatroomsResponse.java
src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
src/main/java/com/poortorich/chat/service/ChatMessageService.java
src/main/java/com/poortorich/chat/service/ChatParticipantService.java
src/main/java/com/poortorich/chat/service/ChatroomService.java
src/main/java/com/poortorich/chat/util/ChatBuilder.java
src/main/java/com/poortorich/chat/validator/ChatroomValidator.java
src/test/java/com/poortorich/chat/controller/ChatParticipantControllerTest.java
src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
src/test/java/com/poortorich/chat/service/ChatMessageServiceTest.java
src/test/java/com/poortorich/chat/service/ChatParticipantServiceTest.java
src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java

#333
- 내가 방장인 채팅방 목록 조회 API
- 방장인 채팅방 목록 조회
- 각 채팅방의 태그, 참여인원수, 마지막 채팅시간 조회

[#333] 내가 방장인 채팅방 목록 조회 API 구현

---

src/main/java/com/poortorich/websocket/stomp/command/subscribe/handler/StompSubscribeHandler.java
src/main/java/com/poortorich/websocket/stomp/command/unsubscribe/handler/StompUnsubscribeHandler.java
src/main/java/com/poortorich/websocket/stomp/service/SubscribeService.java

- 실시간 읽음 처리 로직 수정
- UNSUBSCRIBE시 Destination 없이 subscription-id로만 구독 해제를 진행함
- 따라서 subscription-id로 채팅방 아이디를 조회하도록 수정

[#428] 실시간 읽음 처리 로직 수정
