- README.md
> docs: 테스트차 README.md 수정

- README.md
Reverts Poor-To-Rich/backend#4
> Revert "docs: 테스트차 README.md 수정"

- src/main/java/PoorToRich/PoorToRich/category/entity/Category.java
> #12 
---
- 카테고리 import 오류 수정
> fix: 카테고리 import 수정

- src/main/java/com/poortorich/auth/constants/AuthResponseMessage.java
- src/main/java/com/poortorich/auth/controller/AuthController.java
- src/main/java/com/poortorich/auth/response/enums/AuthResponse.java
- src/main/java/com/poortorich/security/constants/SecurityConstants.java
> [#51] HTTPS 연결을 위한 healthCheck API 추가

- src/main/java/com/poortorich/security/constants/SecurityConstants.java
> [#63] 프론트엔드 CORS 설정

- src/main/java/com/poortorich/user/constants/UserResponseMessages.java
대문자도 하나 이상 들어가야하나 안내 메시지에 명시되어있지 않아 추가
> [#73] 비밀번호 응답 메시지 수정

- src/main/java/com/poortorich/user/constants/UserResponseMessages.java
- src/main/java/com/poortorich/user/controller/UserController.java
- src/main/java/com/poortorich/user/facade/UserFacade.java
- src/main/java/com/poortorich/user/response/UserEmailResponse.java
- src/main/java/com/poortorich/user/response/enums/UserResponse.java
- src/main/java/com/poortorich/user/service/UserService.java
- src/test/java/com/poortorich/user/controller/UserControllerTest.java
- src/test/java/com/poortorich/user/facade/UserFacadeTest.java
- src/test/java/com/poortorich/user/service/UserServiceTest.java
> [#80] 회원 이메일 조회 API

- src/main/java/com/poortorich/security/constants/SecurityConstants.java
> [#89] CORS 설정 추가

- src/main/java/com/poortorich/user/constants/UserResponseMessages.java
- src/main/java/com/poortorich/user/controller/UserController.java
- src/main/java/com/poortorich/user/facade/UserFacade.java
- src/main/java/com/poortorich/user/response/enums/UserResponse.java
- src/main/java/com/poortorich/user/service/UserResetService.java
- src/main/java/com/poortorich/user/service/UserService.java
> [#132] 회원탈퇴 API

- src/main/java/com/poortorich/report/constants/ReportResponseMessages.java
- src/main/java/com/poortorich/report/controller/ReportController.java
- src/main/java/com/poortorich/report/facade/ReportFacade.java
- src/main/java/com/poortorich/report/response/DailyFinance.java
- src/main/java/com/poortorich/report/response/MonthlyTotalResponse.java
- src/main/java/com/poortorich/report/response/enums/ReportResponse.java
- src/main/java/com/poortorich/report/service/ReportService.java
> feat: 월별 수입/지출 합계 API

- src/main/java/com/poortorich/report/constants/ReportResponseMessages.java
- src/main/java/com/poortorich/report/controller/ReportController.java
- src/main/java/com/poortorich/report/facade/ReportFacade.java
- src/main/java/com/poortorich/report/response/Logs.java
- src/main/java/com/poortorich/report/response/WeeklyTotalReportResponse.java
- src/main/java/com/poortorich/report/response/enums/ReportResponse.java
- src/main/java/com/poortorich/report/service/ReportService.java
#154 
- 주별 수입/지출 명세 API 구현
- `MonthlyLogs`를 `Logs`로 통합 -> Monthly와 Weekly에서 모두 사용
> [#154] 주별 수입/지출 명세 API 구현

- src/main/java/com/poortorich/auth/jwt/util/JwtTokenManager.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> test: 테스트용 도메인 추가

- src/main/java/com/poortorich/auth/jwt/util/JwtTokenManager.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> style: 도메인 오타 수정

- src/main/java/com/poortorich/auth/jwt/constants/JwtConstants.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> style: 쿠키 PATH 값 수정

- src/main/java/com/poortorich/auth/jwt/util/JwtTokenManager.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> style: 도메인 삭제

- src/main/java/com/poortorich/report/facade/ReportFacade.java
#176 
- 필드명 수정에서 누락된 빌드 필드명 수정
> [#176] 월별 수입지출 명세 응답 빌드 수정

- src/main/java/com/poortorich/user/entity/enums/Gender.java
프론트 요청에 따라 Gender를 영어값 그대로 전달하도록 수정했습니다.
> [#182] Gender 한글 포맷팅 로직 삭제

- src/main/java/com/poortorich/chart/response/PeriodTotal.java
- src/main/java/com/poortorich/chart/service/ChartService.java
- src/main/java/com/poortorich/chart/util/AmountFormatter.java
* 금액 단위에 **억**, **조** 단위를 추가하였음. 
**경**부터는 오버플로우로 인해 불가함
> [#191] 금액 포맷팅 단위 추가

- src/main/java/com/poortorich/accountbook/response/AccountBookInfoResponse.java
- src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
#207 
- 프론트 요청에 따라 AccountBookInfo 응답에 날짜 필드를 추가
> [#207] AccountBookInfo 응답에 날짜 필드 추가

- src/main/java/com/poortorich/chart/facade/ChartFacade.java
> [#214] aggregatedData 비율 조정

- src/main/java/com/poortorich/s3/constants/S3Constants.java
- src/main/java/com/poortorich/s3/service/FileUploadService.java
- 프로필 변경을 하지 않은 경우 field가 null로 오게되어 NullPointerException 발생
-  Null인지 조사하는 조건문을 추가하였음
> [#218] 프로필 편집 버그 수정

- src/main/java/com/poortorich/accountbook/service/AccountBookService.java
- src/main/java/com/poortorich/report/facade/ReportFacade.java
- src/main/java/com/poortorich/report/service/ReportService.java
#220
- 주어진 기간의 총 트랜잭션 개수를 반환하도록 로직을 수정하였습니다.
>
> [#220] 주별 상세 내역 응답값 수정

- src/main/java/com/poortorich/global/aop/LogAspect.java
#230 
- 로그 관련해서 값이 예외를 반환하는 경우 null 반환하도록 작성된 코드를 수정하였습니다.
> [#230] 로깅 재설정

- src/main/java/com/poortorich/global/aop/LogAspect.java
#232 
- 예외 로깅 설정을 변경하였습니다.
변경전
변경후
> [#232] 로그 설정 변경

- src/test/java/com/poortorich/auth/service/AuthServiceTest.java
새로 추가된 메소드 호출 로직에 반환값을 설정하여 추가함
> [#245] 로그인 테스트 코드 오류 수정

- src/main/java/com/poortorich/category/repository/CategoryRepository.java
- src/main/java/com/poortorich/category/service/CategoryService.java
- src/main/java/com/poortorich/iteration/entity/enums/Weekday.java
- src/main/java/com/poortorich/iteration/provider/IterationCalculatorProvider.java
#251 
- `주중 매일` 로직 사용시 모든 요일이 반복되던 오류 수정
- 카테고리 차트 조회시 삭제된 사용자화 카테고리의 상세 페이지에 들어가는 경우 404 에러가 뜨는 오류 수정
- 카테고리 조회 로직 수정
> [#251] QA 오류 수정

- Dockerfile
- src/main/java/com/poortorich/category/repository/CategoryRepository.java
- src/main/java/com/poortorich/category/service/CategoryService.java
- src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
- src/main/java/com/poortorich/income/facade/IncomeFacade.java
- src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
#295
- 가계부 편집시 카테고리 조회 로직 수정
- 삭제된 카테고리도 조회할 수 있도록 수정
> [#295] 가계부 편집 오류 수정

- src/main/java/com/poortorich/security/constants/SecurityConstants.java
#298
- 프론트엔드 성능 테스트를 위한 CORS 설정 추가
> [#298] CORS 설정 추가

- src/main/java/com/poortorich/auth/oauth2/handler/CustomOAuth2LoginSuccessHandler.java
> [#304] 카카오 로그인 리다이렉션 경로 수정

- src/main/java/com/poortorich/category/entity/Category.java
- src/main/java/com/poortorich/expense/entity/Expense.java
- src/main/java/com/poortorich/income/entity/Income.java
- src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
- src/main/java/com/poortorich/iteration/entity/IterationIncomes.java
- src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
- src/main/java/com/poortorich/iteration/entity/info/MonthlyIterationRule.java
- src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
- src/main/java/com/poortorich/user/entity/User.java
#314
- entity DB 필드명을 컨벤션에 맞게 수정
> [#314] entity 필드명 수정

- build.gradle
- src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
- src/main/java/com/poortorich/chat/facade/ChatFacade.java
- src/main/java/com/poortorich/chat/request/ChatroomUpdateRequest.java
- src/main/java/com/poortorich/chat/response/ChatroomInfoResponse.java
- src/main/java/com/poortorich/chat/util/ChatBuilder.java
- 프로필 이미지 로직과 일치할 수 있도록 조회/편집에 `isDefaultImage` 필드를 추가했습니다.
> [#338] 채팅방 편집/조회 필드 추가

- src/main/java/com/poortorich/auth/service/AuthService.java
- src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
> [#389] 토큰 재발급 액세스 토큰 제공 오류 수정

- src/main/java/com/poortorich/chat/util/manager/ChatroomLeaveManager.java
- src/main/java/com/poortorich/report/repository/ReportRepository.java
- src/main/java/com/poortorich/report/service/ReportService.java
> [#515] 채팅방 삭제 로직에 기능 추가
